export {
  GET_BOARD_SHARES_QUERY,
  GET_SHARED_BOARDS_QUERY,
  SHARE_BOARD_MUTATION,
  UPDATE_BOARD_SHARE_MUTATION,
  REMOVE_BOARD_SHARE_MUTATION,
  GENERATE_SHARE_LINK_MUTATION,
  REVOKE_SHARE_LINK_MUTATION,
} from './api';
