-- Canonical fresh-install schema for the Board Manager application.
-- Safe to run in a new Supabase PostgreSQL database. No application data is inserted.

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'board_type') THEN
    CREATE TYPE board_type AS ENUM ('NOTICE_BOARD', 'CHECKLIST', 'EVENTS');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('OWNER', 'EDITOR', 'VIEWER');
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth0_id TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  name TEXT,
  picture TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS boards (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  board_type board_type NOT NULL,
  description TEXT,
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  share_token TEXT UNIQUE,
  google_calendar_id TEXT,
  google_calendar_name TEXT,
  google_access_token TEXT,
  google_refresh_token TEXT,
  google_token_expires_at TIMESTAMP,
  calendar_sync_range_days INTEGER NOT NULL DEFAULT 14
    CHECK (calendar_sync_range_days BETWEEN 1 AND 365),
  calendar_last_sync_at TIMESTAMP,
  calendar_connected_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_boards (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  board_id INTEGER NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  role user_role NOT NULL,
  PRIMARY KEY (user_id, board_id)
);

CREATE TABLE IF NOT EXISTS items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id INTEGER NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  details TEXT,
  is_checked BOOLEAN NOT NULL DEFAULT FALSE,
  category TEXT,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  google_event_id TEXT,
  event_start_time TIMESTAMP,
  event_end_time TIMESTAMP,
  event_description TEXT,
  google_calendar_link TEXT,
  deleted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (event_end_time IS NULL OR event_start_time IS NULL OR event_end_time >= event_start_time)
);

CREATE TABLE IF NOT EXISTS board_shares (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id INTEGER NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  shared_with_user_id TEXT NOT NULL,
  shared_by_user_id TEXT NOT NULL,
  permission_level TEXT NOT NULL CHECK (permission_level IN ('VIEW', 'EDIT', 'ADMIN')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (board_id, shared_with_user_id)
);

CREATE INDEX IF NOT EXISTS idx_boards_created_at ON boards(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_boards_google_calendar
  ON boards(google_calendar_id)
  WHERE google_calendar_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_boards_share_token
  ON boards(share_token)
  WHERE share_token IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_user_boards_board_id ON user_boards(board_id);

CREATE INDEX IF NOT EXISTS idx_items_board_active
  ON items(board_id, category, created_at)
  WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_items_google_event_id
  ON items(google_event_id)
  WHERE google_event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_items_event_start_time
  ON items(event_start_time)
  WHERE event_start_time IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_board_shares_board_id ON board_shares(board_id);
CREATE INDEX IF NOT EXISTS idx_board_shares_shared_with ON board_shares(shared_with_user_id);
CREATE INDEX IF NOT EXISTS idx_board_shares_shared_by ON board_shares(shared_by_user_id);

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS boards_set_updated_at ON boards;
CREATE TRIGGER boards_set_updated_at
BEFORE UPDATE ON boards
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS items_set_updated_at ON items;
CREATE TRIGGER items_set_updated_at
BEFORE UPDATE ON items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS board_shares_set_updated_at ON board_shares;
CREATE TRIGGER board_shares_set_updated_at
BEFORE UPDATE ON board_shares
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- Keep Supabase Data API access denied by default.
-- The application currently authorizes through Auth0 and server-side pg queries,
-- so explicit client policies should be added only after mapping Auth0 claims.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE boards ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_boards ENABLE ROW LEVEL SECURITY;
ALTER TABLE items ENABLE ROW LEVEL SECURITY;
ALTER TABLE board_shares ENABLE ROW LEVEL SECURITY;

COMMIT;
